# Template created by hash
Description: Creates a standalone EC2 instance to use as a jump host to Connect 2 instances
Parameters:

  ImageId:
    Description: AMI Id of the latest Some RHEL image
    Type: String

  InstanceProfile:
    Description: ARN of the Instance Profile
    Type: String

  InstanceType:
    Description: The EC2 instance type to launch
    Type: String
    AllowedValues:
    - c4.2xlarge
    - c4.4xlarge
    - c4.8xlarge
    - c4.large
    - c4.xlarge
    - m4.10xlarge
    - m4.16xlarge
    - m4.2xlarge
    - m4.4xlarge
    - m4.large
    - m4.xlarge
    - r4.16xlarge
    - r4.2xlarge
    - r4.4xlarge
    - r4.8xlarge
    - r4.large
    - r4.xlarge
    - t2.2xlarge
    - t2.large
    - t2.medium
    - t2.micro
    - t2.nano
    - t2.small
    - t2.xlarge

  KeyName:
    Type: String

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id

  SubnetId:
    Type: AWS::EC2::Subnet::Id

  AvailabilityZone:
    Type: String
    AllowedValues:
      - A
      - B
      - C

  # Tagging Parameters
  Environment:
    Type: String
    AllowedValues:
      - Production
      - UAT
      - Test

  BusinessUnit:
    Type: String
    AllowedValues:
      - Charitable
      - Corporate
      - Gaming
      - Lotteries
      - Wagering
    ConstraintDescription: Must be Charitable | Corporate | Gaming | Lotteries | Wagering

  Department:
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: BrandName

  Application:
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: SomePlatform

  Component:
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: Bastion

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      IamInstanceProfile: !Ref InstanceProfile
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds:
      - !Ref SecurityGroup
      SubnetId: !Ref SubnetId
      Tags:
      - Key: Name
        Value:  !Sub ${Environment}-${Component}-${AvailabilityZone}
      - Key: Environment
        Value: !Ref Environment
      - Key: BusinessUnit
        Value: !Ref BusinessUnit
      - Key: Application
        Value: !Ref Application
      - Key: Component
        Value: !Ref Component

  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref Instance

Outputs:
  Instance:
    Description: Instance ID
    Value: !Ref Instance

  ElasticIP:
    Description: The Public IP associated with the instance
    Value: !Ref ElasticIP
