# Template created by hash
Description: CloudFront distribution stack
Parameters:

  PriceClass:
    Type: String
    AllowedValues:
    - PriceClass_All
    - PriceClass_200
    - PriceClass_100

  CloudFrontTTL:
    Type: Number
    MinValue: 0
    MaxValue: 31536000

  VPCId:
    Type: AWS::EC2::VPC::Id

  OriginId:
    Type: String

  ELBDNSName:
    Type: String

  SSLCertArn:
    Type: String

  WebACLId:
    Type: String

  HostName:
    Type: String

  DomainName:
    Type: String

  # Tagging Parameters
  # Note that CloudFormation does not support tagging CLoudFront distributions (Sept 2017)
  Environment:
    Type: String
    AllowedValues:
      - Production
      - UAT
      - Test

  BusinessUnit:
    Type: String
    AllowedValues:
      - Charitable
      - Corporate
      - Gaming
      - Lotteries
      - Wagering
    ConstraintDescription: Must be Charitable | Corporate | Gaming | Lotteries | Wagering

  Department:
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: BrandName

  Application:
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: SomePlatform

  Component:
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: CDN

Conditions:
  CFCustomSSL: !Not [!Equals [!Ref SSLCertArn, '']]
  IsRootDomain: !Equals [ !Ref HostName, '' ]

Resources:
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Ref ELBDNSName
          Id: !Ref OriginId
          CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: match-viewer
            OriginSSLProtocols:
            - TLSv1.2
        Enabled: true
        Comment: !Sub ${Environment} ${Component} ELB
        Aliases:
         - !If [ IsRootDomain, !Ref DomainName, !Sub "${HostName}.${DomainName}" ]
        DefaultCacheBehavior:
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          TargetOriginId: !Ref OriginId
          ForwardedValues:
            QueryString: 'true'
            Headers:
            - '*'
            Cookies:
              Forward: all
          ViewerProtocolPolicy: allow-all
          Compress: 'true'
        Restrictions:
          GeoRestriction:
            RestrictionType: whitelist
            Locations:
            - AU
        WebACLId: !Ref WebACLId
        PriceClass: !Ref PriceClass
        ViewerCertificate: !If [ CFCustomSSL, {AcmCertificateArn: !Ref 'SSLCertArn', SslSupportMethod: sni-only}, {CloudFrontDefaultCertificate: 'true'} ]

Outputs:
  Distribution:
    Value: !Ref Distribution

  CloudFrontDNSName:
    Value: !GetAtt [ Distribution, DomainName ]
