# Template created by hash
Description: IAM Policy for EC2 Instances to allow S3 access to the build bucket, CloudFormation access, and logging
Parameters:
  BuildBucket:
    Description: Bucket used for pulling data and applications on build
    Type: String
    Default: dchash2buildbucket
  AppBucket:
    Description: Bucket used for storing applicaton code
    Type: String
    Default: DCHash2-nonprod-applications
Resources:
  Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for Application Tier EC2 instances to allow S3 access to the build bucket, CloudFormation access, and logging
      Path: "/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Sid: S3Allow
          Effect: Allow
          Action:
          - s3:GetObject
          - S3:GetObjectAcl
          - s3:ListBucket
          - s3:GetBucketLocation
          - s3:RestoreObject
          - s3:ListAllMyBuckets
          - s3:GetBucketAcl,
          - s3:GetBucketVersioning
          - s3:GetBucketPolicy
          Resource:
          - !Join [ "", [ "arn:aws:s3:::", !Ref BuildBucket ] ]
          - !Join [ "", [ "arn:aws:s3:::", !Ref BuildBucket, "/*" ]]
        - Sid: CloudFormationAccess
          Effect: Allow
          Action:
          - cloudformation:SignalResource
          - cloudformation:DescribeStackResource
          - cloudformation:CreateStack
          - cloudformation:DescribeStacks
          - cloudformation:DescribeStackEvents
          - cloudformation:GetTemplate
          - cloudformation:ValidateTemplate
          - cloudformation:ListStacks
          - cloudformation:ListStackResources
          Resource: "*"
        - Sid: MetricsAccess
          Effect: Allow
          Action:
          - cloudwatch:PutMetricData
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:DescribeLogGroups
          - logs:DescribeLogStreams
          - logs:PutLogEvents
          Resource: "*"
        - Sid: CodeDeploy
          Effect: Allow
          Action:
          - s3:Get*
          - s3:List*
          Resource:
          - !Sub arn:aws:s3:::${AppBucket}
          - !Sub arn:aws:s3:::${AppBucket}/*
          - arn:aws:s3:::aws-codedeploy-ap-southeast-2/*
Outputs:
  InstancePolicyARN:
    Value:
      Ref: Policy
    Export:
      Name: !Sub "${AWS::StackName}-IAMPolicyARN"
