# Template created by hash
Description: Create a Record Set in a Hosted Zone in Route 53
Parameters:

  AliasTarget:
    Type: String

  AliasHostedZoneId:
    Type: String

  HostedZoneName:
    Type: String

  RecordType:
    Type: String
    AllowedValues:
    - A
    - CNAME
    - MX
    - AAAA
    - TXT
    - PTR
    - SVR
    - SPF
    - NAPTR
    - CAA
    - NS
    - SOA

  HostName:
    Type: String

  DomainName:
    Type: String

  TTL:
    Type: String

  DestinationAddress:
    Type: String

Conditions:
  IsAlias: !Not [ !Equals [ !Ref AliasTarget, '' ]]
  IsNotAlias: !Equals [ !Ref AliasTarget, '' ]
  IsRootDomain: !Equals [ !Ref HostName, '' ]

Resources:
  AliasRecordSet:
    Condition: IsAlias
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
         DNSName: !Ref AliasTarget
         HostedZoneId: !Ref AliasHostedZoneId
      HostedZoneName: !Sub ${DomainName}.
      Name: !If [ IsRootDomain, !Sub "${DomainName}.", !Sub "${HostName}.${DomainName}." ]
      Type: !Ref RecordType

  RecordSet:
    Condition: IsNotAlias
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub ${DomainName}.
      Name: !Sub ${HostName}.${DomainName}.
      TTL: !Ref TTL
      Type: !Ref RecordType
      ResourceRecords:
      - !Ref DestinationAddress

#  RootDomainRecordSet:
#    Condition: IsRootDomain
#    Type: AWS::Route53::RecordSet
#    Properties:
#      AliasTarget:
#         DNSName: !Ref AliasTarget
#         HostedZoneId: !Ref AliasHostedZoneId
#      HostedZoneName: !Sub ${DomainName}.
#      Name: !Sub ${DomainName}.
#      Type: !Ref RecordType

Outputs:
  AliasRecordSet:
    Condition: IsAlias
    Description: Alias Record Set
    Value: !Ref AliasRecordSet
    Export:
      Name: !Sub ${AWS::StackName}-AliasRecordSet

  RecordSet:
    Condition: IsNotAlias
    Description: Record Set
    Value: !Ref RecordSet
    Export:
      Name: !Sub ${AWS::StackName}-RecordSet
