# Template created by hash
Description: ElastiCache with Redis 3.2.4
Parameters:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id

# ElastiCache Cluster Parameters
# To enable multi-AZ failover, cachenodetype cannot be t1 or t2 node types
# Redis backup and restore is not supported for T2 instances
  CacheNodeType:
    Type: String
    AllowedValues:
    - cache.t2.micro
    - cache.t2.small
    - cache.t2.medium
    - cache.m4.large
    - cache.m4.xlarge
    - cache.m4.2xlarge

  AutoFailover:
    Type: String
    AllowedValues:
    - true
    - false

# Number of cache nodes must be more than 1 if auto-failover is enabled
  NumberofCacheClusters:
    Type: Number
    MinValue: 1
    MaxValue: 3

  Port:
    Type: Number
    MinValue: 1024
    MaxValue: 65535

  MaintenanceWindow:
    Type: String

#  SnapshotWindow:
#    Description: Time of day in 24 time to take a daily snapshot of the ElastiCache
#    Type: String
#    Default: "05:00-07:00"
#
#  SnapshotRetention:
#    Description: Number of days to retain ElastiCache snapshots
#    Type: Number
#    Default: 5

  ParameterGroupVersion:
    Type: String

  VPCID:
    Type: AWS::EC2::VPC::Id

  #The Subnets to be used for the Auto Scaling Group
  # Needs to be specified otherwise default VPC is used.
  SubnetList:
    Type: List<AWS::EC2::Subnet::Id>

# Tagging Parameters
  Environment:
    Type: String
    AllowedValues:
      - Production
      - UAT
      - Test
  BusinessUnit:
    Type: String
    AllowedValues:
      - Charitable
      - Corporate
      - Gaming
      - Lotteries
      - Wagering
    ConstraintDescription: Must be Charitable | Corporate | Gaming | Lotteries | Wagering
  Department:
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: BrandName

  Application:
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: SomePlatform

  Component:
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: ElastiCache-Redis

Resources:

  SubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Subnet Group for Connect 2 ElastiCache cluster
      SubnetIds: !Ref SubnetList

  ParameterGroup:
    Type: AWS::ElastiCache::ParameterGroup
    Properties:
      Description: !Sub ${Environment}-${Application}-ParameterGroup-${ParameterGroupVersion}
      Properties: !Ref AWS::NoValue
      CacheParameterGroupFamily: redis3.2

  ReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupDescription: !Sub ${Environment} ${Application} Redis ElastiCache
      # ReplicationGroupId cannot be more than 20 characters (Sept 2017)
      ReplicationGroupId: !Sub ${Environment}-C2
      Engine: redis
      AutomaticFailoverEnabled: !Ref AutoFailover
      CacheNodeType: !Ref CacheNodeType
      CacheParameterGroupName: !Ref ParameterGroup
      CacheSubnetGroupName: !Ref SubnetGroup
      EngineVersion: 3.2.4
      NumCacheClusters: !Ref NumberofCacheClusters
      Port: !Ref Port
      PreferredMaintenanceWindow: !Ref MaintenanceWindow
#TODO
#      SnapshotWindow: !Ref SnapshotWindow
#      SnapshotRetentionLimit: !Ref SnapshotRetention
      SecurityGroupIds:
      - !Ref SecurityGroup
      Tags:
       - Key: Name
         Value: !Sub ${Environment}-${Component}
       - Key: BusinessUnit
         Value: !Ref BusinessUnit
       - Key: Environment
         Value: !Ref Environment
       - Key: Department
         Value: !Ref Department
       - Key: Component
         Value: !Ref Component

Outputs:
  CacheConnection:
    Description: ElastiCache Connection address
    Value:
      Fn::Join: [ ":", [ !GetAtt [ ReplicationGroup, PrimaryEndPoint.Address ], !GetAtt [ ReplicationGroup, PrimaryEndPoint.Port ] ]]
