# Template created by hash
Description: IAM Role for CodeDeploy
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Sid: "CodeDeploy"
          Effect: Allow
          Principal:
            Service: codedeploy.ap-southeast-2.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      RoleName: CodeDeploy-Sydney-ServiceRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole
Outputs:
  IAMRoleName:
    Value: !Ref Role
    Export:
      Name: !Sub "${AWS::StackName}-RoleName"
  IAMRoleARN:
    Value: !GetAtt [ Role, Arn]
    Export:
      Name: !Sub "${AWS::StackName}-RoleARN"
