# Template created by hash
Description: "IAM Role and Policy for VPC Flow Logs"
Resources:
  ManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Allows a VPC to push Flow Logs to CloudWatch
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Sid: FlowLogsAllow
          Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
          Effect: Allow
          Resource: "*"
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Sid: "FlowLogsInlineAllow"
          Effect: Allow
          Principal:
            Service: vpc-flow-logs.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns: [ !Ref ManagedPolicy ]
      #Note: Defining a role name does not allow multiple stacks to be
      # created in the same account as it tries to create a role with the same name multiple times.
      #RoleName: VPC-FlowLogs
Outputs:
  IAMRoleName:
    Value: !Ref Role
    Export:
      Name: !Sub "${AWS::StackName}-FlowLogsRoleName"
  IAMRoleARN:
    Value: !GetAtt [ Role, Arn]
    Export:
      Name: !Sub "${AWS::StackName}-FlowLogsRoleARN"
