# Template created by hash
Description: Creates and configures a RDS Aurora Cluster (Multi-AZ) with Encrypted Storage. Depending on input different configurations will apply
  Production and PreProd - Multi-AZ, 14 Day Automated Backups, Enhanced Monitoring (30 sec intervals), Preferred Maintance Window Monday 4-4:30AM, Backup Windows 3-4 AM
  Test - Single-AZ, No Automated Backups, No Enhanced Monitoring, Preferred Maintance Window Monday 4-4:30AM, No Backup Window

Parameters:

  VPCID:
    Type: AWS::EC2::VPC::Id

  DBSubnetList:
    Type: List<AWS::EC2::Subnet::Id>

  VPCCIDR:
    Type: String

  # NOTE:
  # List of Instance Types only includes
  # types that allow for EBS Encryption:
  # M3, M4, T2 (from .small up), R3
  # See: http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.Encryption.html#Overview.Encryption.Availability
  DBInstanceClass:
    Type: String
    AllowedValues:
    - db.m3.2xlarge
    - db.m3.large
    - db.m3.medium
    - db.m3.xlarge
    - db.m4.10xlarge
    - db.m4.2xlarge
    - db.m4.4xlarge
    - db.m4.large
    - db.m4.xlarge
    - db.r3.2xlarge
    - db.r3.4xlarge
    - db.r3.8xlarge
    - db.r3.large
    - db.r3.xlarge
    - db.t2.large
    - db.t2.medium
    - db.t2.small
    Default: db.t2.small

  DBInstanceName:
    Type: String
    AllowedPattern: "[a-z0-9]+"

  MasterUsername:
    Type: String

  MasterPassword:
    Type: String
    NoEcho: True

  DBPort:
    Type: Number

  PreferredBackupWindow:
    Type: String

  PreferredMaintenanceWindow:
    Type: String

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id

# Tagging Parameters
  Environment:
    Type: String
    AllowedValues:
      - Production
      - UAT
      - Test

  BusinessUnit:
    Type: String
    AllowedValues:
      - Charitable
      - Corporate
      - Gaming
      - Lotteries
      - Wagering
    ConstraintDescription: Must be Charitable | Corporate | Gaming | Lotteries | Wagering

  Department:
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: BrandName

  Application:
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: SomePlatform

  Component:
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: Aurora

Mappings:

  EnvironmentConfig:
    Production:
      MultiAZ: True
      MonitoringInterval: 30
      BackupRetentionPeriod: 14

    UAT:
      MultiAZ: True
      MonitoringInterval: 30
      BackupRetentionPeriod: 14

    Test:
      MultiAZ: False
      MonitoringInterval: 0
      BackupRetentionPeriod: 1

Conditions:
  IsProduction: !Or [ !Equals [ !Ref Environment, Production], !Equals [ !Ref Environment, UAT ] ]

Resources:

    MonitoringRole:
      Condition: IsProduction
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Sid: "RDSEnhancedMonitoringRole"
            Effect: Allow
            Principal:
              Service: monitoring.rds.amazonaws.com
            Action: sts:AssumeRole
        Path: "/"
        ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole

    DBClusterParameterGroup:
      Type: AWS::RDS::DBClusterParameterGroup
      Properties:
        Family: aurora5.6
        Description: !Sub DBCluster Parameter Group for ${Environment}-${Application}
        Parameters:
          character_set_database: utf32

    DBParameterGroup:
      Type: AWS::RDS::DBParameterGroup
      Properties:
        Family: aurora5.6
        Description: !Sub DB Parameter Group for ${Environment}-${Application}
        Parameters:
          sql_mode: IGNORE_SPACE

    DBSubnetGroup:
      Type: AWS::RDS::DBSubnetGroup
      Properties:
        DBSubnetGroupDescription: String
        SubnetIds: !Ref DBSubnetList

    AuroraCluster:
      Type: AWS::RDS::DBCluster
      DeletionPolicy: Snapshot
      Properties:
        Engine: aurora
        MasterUsername: !Ref MasterUsername
        MasterUserPassword: !Ref MasterPassword
        BackupRetentionPeriod: !FindInMap [EnvironmentConfig, !Ref Environment, BackupRetentionPeriod ]
        PreferredBackupWindow: !Ref PreferredBackupWindow
        PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
        DBSubnetGroupName: !Ref DBSubnetGroup
        DBClusterParameterGroupName: !Ref DBClusterParameterGroup
        Port: !Ref DBPort
        StorageEncrypted: True
        VpcSecurityGroupIds:
        - !Ref SecurityGroup

    AuroraInstance:
      Type: AWS::RDS::DBInstance
      Properties:
        Engine: aurora
        DBName: !Ref DBInstanceName
        DBInstanceClass: !Ref DBInstanceClass
        DBParameterGroupName: !Ref DBParameterGroup
        DBClusterIdentifier: !Ref AuroraCluster
        MonitoringInterval: !FindInMap [EnvironmentConfig, !Ref Environment, MonitoringInterval ]
        MonitoringRoleArn: !If [IsProduction, !GetAtt [ MonitoringRole, "Arn"],  !Ref "AWS::NoValue" ]


Outputs:

  EndPointAddress:
    Description: The EndPoint Adress of the RDS Aurora Cluster
    Value: !GetAtt [ AuroraCluster, Endpoint.Address]

  EndPointPort:
    Description: The EndPoint Port of the RDS Aurora Cluster
    Value: !GetAtt [ AuroraCluster, Endpoint.Port]

  ReaderEndPoint:
    Description: The Reader EndPoint Port of the RDS Aurora Cluster
    Value: !GetAtt [ AuroraCluster, ReadEndpoint.Address]
