# Template created by hash
Description: Create S3 Bucket to upload all templates in it. But it is generic template for any name for any purpose with retain policy which means if yo delet the stack the bucket will not delete
Parameters:

# Lets create a bucket which is already placed in other templates DCHash2buildbucket
  S3BucketName:
    Description: The name of the Amazon S3 bucket
    Type: String
    Default: dchash2buildbucket

  # Tagging Parameters
  Environment:
    Description: Production or PreProduction or Test
    Type: String
    Default: PreProduction
    AllowedValues:
      - Production
      - PreProduction
      - Test

  BusinessUnit:
    Description: Some Group Business Unit
    Type: String
    Default: Gaming
    AllowedValues:
      - Charitable
      - Corporate
      - Gaming
      - Lotteries
      - Wagering
    ConstraintDescription: Must be Charitable | Corporate | Gaming | Lotteries | Wagering

  Department:
    Description: Department
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: BrandName

  Application:
    Description: Application
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: SomePlatform

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName:
        Ref: S3BucketName
      Tags:
      - Key: Name
        Value: !Ref S3BucketName
      - Key: Environment
        Value: !Ref Environment
      - Key: BusinessUnit
        Value: !Ref BusinessUnit
      - Key: Department
        Value: !Ref Department
      - Key: Application
        Value: !Ref Application

Outputs:
  S3BucketName:
    Description: Name of the S3 bucket
    Value: !Ref S3Bucket
    Export:
      Name: !Sub ${AWS::StackName}-S3BucketName
