# Template created by hash
Description: Create S3 Bucket with policy for ELB Access Logs
Parameters:

  S3BucketName:
    Description: The name of the Amazon S3 bucket
    Type: String
    Deafult: DCHash2ELBAccessLogs

  LogAccessControl:
    ConstraintDescription: Must be either AuthenticatedRead, AwsExecRead, BucketOwnerRead,
      BucketOwnerFullControl, LogDeliveryWrite, Private, PublicRead or PublicReadWrite.
    Type: String
    AllowedValues:
    - AuthenticatedRead
    - AwsExecRead
    - BucketOwnerRead
    - BucketOwnerFullControl
    - LogDeliveryWrite
    - Private
    - PublicRead
    - PublicReadWrite

  # Tagging Parameters
  Environment:
    Description: Production or UAT or Test
    Type: String
    Default: UAT
    AllowedValues:
      - Production
      - UAT
      - Test

  BusinessUnit:
    Description: Some Group Business Unit
    Type: String
    Default: Gaming
    AllowedValues:
      - Charitable
      - Corporate
      - Gaming
      - Lotteries
      - Wagering
    ConstraintDescription: Must be Charitable | Corporate | Gaming | Lotteries | Wagering

  Department:
    Description: Department
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: BrandName

  Application:
    Description: Application
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: SomePlatform

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName:
        Ref: S3BucketName
      Tags:
      - Key: Name
        Value: !Ref S3BucketName
      - Key: Environment
        Value: !Ref Environment
      - Key: BusinessUnit
        Value: !Ref BusinessUnit
      - Key: Department
        Value: !Ref Department
      - Key: Application
        Value: !Ref Application

  S3LoggingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Version: '2008-10-17'
        Statement:
        - Action:
          - s3:PutObject
          Sid: AccessLogs
          Resource: !Sub arn:aws:s3:::${S3BucketName}/*
          Effect: Allow
          Principal:
            AWS:
            # This is the ELB resource - all ELBs in region are controlled by AWS account XXXXXXXXXXXX. This is prod account.
              - "arn:aws:iam::XXXXXXXXXXXX:root" # This id prod account. There are two account 1 for Test and UAT and the other one is for prod 
            # This is the CloudFormation role in the DCHash2 NonProd AWS account. It is required so that the ELB template can create folders in the bucket. This is non-prod account
              - "arn:aws:iam::XXXXXXXXXXXX:role/Cloudformation-Role" # This is non-prod account
      Bucket: !Ref S3BucketName

Outputs:
  S3BucketName:
    Description: Name of the S3 bucket
    Value: !Ref S3Bucket
    Export:
      Name: !Sub ${AWS::StackName}-S3BucketName
