# Template created by hash
Description: Creates a new S3 bucket for CloudTrail Logs
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName:
        Fn::Join:
        - "-"
        - - Ref: "AWS::AccountId"
          - cloudtrail
      Tags:
      - Key: Name
        Value:
          Fn::Join:
          - "-"
          - - Ref: "AWS::AccountId"
            - CloudTrail
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: Bucket
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Sid: AWSCloudTrailAclCheck
          Effect: Allow
          Principal:
            Service: cloudtrail.amazonaws.com
          Action: s3:GetBucketAcl
          Resource:
            Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - Ref: Bucket
        - Sid: AWSCloudTrailWrite
          Effect: Allow
          Principal:
            Service: cloudtrail.amazonaws.com
          Action: s3:PutObject
          Resource:
            Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - Ref: Bucket
              - "/AWSLogs/"
              - Ref: "AWS::AccountId"
              - "/*"
          Condition:
            StringEquals:
              s3:x-amz-acl: "bucket-owner-full-control"
Outputs:
  CloudTrailBucketName:
    Description: Resource name of the S3 bucket
    Value:
      Ref: Bucket
    Export:
      Name: !Sub "${AWS::StackName}-CloudTrailBucketName"
