# Template created by hash
Description: Master CloudFormation Template to create one public and one private Route 53 Hosted Zone
Parameters:

  # Route 53 Template URL
  Route53TemplateFile:
    Type: String
    Default: Route53-HostedZone.yaml

  BuildBucket:
    Description: Name of the build bucket containing the CloudFormation templates
    Type: String
    Default: dchash2buildbucket

  #Route53 Parameters
  ExternalDomain:
    Description: The Domain Name of the Public Hosted Zone. Ignore if creating a Private Hosted Zone
    Type: String
    Default: uat.ClientPlatformName.com.au

  VPCStackName:
    Description: Provide the name of the CloudFormation stack that built the VPC
    Type: String
    Default: UAT-VPC

  # Tagging Parameters
  Environment:
    Description: Production or UAT or Test
    Type: String
    Default: UAT
    AllowedValues:
      - Production
      - UAT
      - Test

  BusinessUnit:
    Description: Some Business Unit
    Type: String
    Default: Gaming
    AllowedValues:
      - Charitable
      - Corporate
      - Gaming
      - Lotteries
      - Wagering
    ConstraintDescription: Must be Charitable | Corporate | Gaming | Lotteries | Wagering

  Department:
    Description: Department
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: SomePlatform

  Application:
    Description: Specific Application
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: DCHash2

Resources:
  PublicHostedZone:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3-ap-southeast-2.amazonaws.com/${BuildBucket}/${Route53TemplateFile}
      Tags:
      - Key: Environment
        Value: !Ref Environment
      - Key: BusinessUnit
        Value: !Ref BusinessUnit
      - Key: Department
        Value: !Ref Department
      - Key: Application
        Value: !Ref Application
      - Key: Component
        Value: Route53HostedZone
      Parameters:
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit
        Department: !Ref Department
        Application: !Ref Application
        Type: Public
        DomainName: !Ref ExternalDomain
        VPCId: ''

  PrivateHostedZone:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3-ap-southeast-2.amazonaws.com/${BuildBucket}/${Route53TemplateFile}
      Tags:
      - Key: Environment
        Value: !Ref Environment
      - Key: BusinessUnit
        Value: !Ref BusinessUnit
      - Key: Department
        Value: !Ref Department
      - Key: Application
        Value: !Ref Application
      - Key: Component
        Value: Route53HostedZone
      Parameters:
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit
        Department: !Ref Department
        Application: !Ref Application
        Type: Private
        DomainName:
          Fn::ImportValue: !Sub ${VPCStackName}-Private-DomainName
        VPCId:
          Fn::ImportValue: !Sub ${VPCStackName}-VPCID

Outputs:
  PublicHostedZoneId:
    Description: The Public Route53 Hosted Zone Identifier
    Value: !GetAtt [ PublicHostedZone, Outputs.HostedZoneId ]
    Export:
      Name: !Sub ${AWS::StackName}-Public-HostedZoneId

  PublicDomainName:
    Description: The Public Domain Name
    Value: !GetAtt [ PublicHostedZone, Outputs.DomainName ]
    Export:
      Name: !Sub ${AWS::StackName}-Public-DomainName

  PrivateHostedZoneId:
    Description: The Private Route53 Hosted Zone Identifier
    Value: !GetAtt [ PrivateHostedZone, Outputs.HostedZoneId ]
    Export:
      Name: !Sub ${AWS::StackName}-Private-HostedZoneId

  PrivateDomainName:
    Description: The Private Domain Name
    Value: !GetAtt [ PrivateHostedZone, Outputs.DomainName ]
    Export:
      Name: !Sub ${AWS::StackName}-Private-DomainName
