# Template created by hash
Description: Creates a Route53 Hosted Zone for DCHash2 Environment

Parameters:

  Type:
    Type: String
    AllowedValues:
    - Public
    - Private

  #Route53 Parameters
  DomainName:
    Type: String

  VPCId:
    Type: String

  # Tagging Parameters
  Environment:
    Type: String
    AllowedValues:
      - Production
      - UAT
      - Test

  BusinessUnit:
    Type: String
    AllowedValues:
      - Charitable
      - Corporate
      - Gaming
      - Lotteries
      - Wagering
    ConstraintDescription: Must be Charitable | Corporate | Gaming | Lotteries | Wagering

  Department:
    Type: String
    MinLength: '3'
    MaxLength: '255'

  Application:
    Type: String
    MinLength: '3'
    MaxLength: '255'

Conditions:
  IsPublic: !Equals [ !Ref Type, "Public" ]
  IsPrivate: !Equals [ !Ref Type, "Private" ]

Resources:

  #Creates a Public Hosted Zone
  #The HostZoneId can be used by downstream stacks to associate with ELB/ALBs etc
  # See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-route53.html
  PublicRoute53HostedZone:
    Type: AWS::Route53::HostedZone
    Condition: IsPublic
    Properties:
      HostedZoneConfig:
        Comment: !Sub Public Hosted Route53 Zone for ${Application}-${Environment}-${Department}
      Name: !Ref DomainName
      HostedZoneTags:
        - Key: Name
          Value:  !Sub ${Environment}-${Application}-Public
        - Key: Environment
          Value: !Ref Environment
        - Key: BusinessUnit
          Value: !Ref BusinessUnit
        - Key: Application
          Value: !Ref Application

  #Creates a Private Hosted Zone
  #The HostZoneId can be used by downstream stacks to associate with ELB/ALBs etc
  # See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-route53.html
  PrivateRoute53HostedZone:
    Type: AWS::Route53::HostedZone
    Condition: IsPrivate
    Properties:
      HostedZoneConfig:
        Comment: !Sub Private Hosted Route53 Zone for ${Application}-${Environment}-${Department}
      Name: !Ref DomainName
      VPCs:
        -
          VPCId: !Ref VPCId
          VPCRegion: !Ref "AWS::Region"
      HostedZoneTags:
        - Key: Name
          Value:  !Sub ${Environment}-${Application}-Private
        - Key: Environment
          Value: !Ref Environment
        - Key: BusinessUnit
          Value: !Ref BusinessUnit
        - Key: Application
          Value: !Ref Application

Outputs:

  HostedZoneId:
    Description: The Route53 Hosted Zone Identifier
    Value: !If [ IsPublic, !Ref PublicRoute53HostedZone, !Ref PrivateRoute53HostedZone ]
    Export:
      Name: !Sub ${AWS::StackName}-${Type}-HostedZoneId

  DomainName:
    Description: The Domain name used for Hosted Zone
    Value: !Ref DomainName
    Export:
      Name: !Sub ${AWS::StackName}-${Type}-DomainName
