# Template created by hash
Description: Creates and Elastic Search Domain for DCHash2

Parameters:

  SearchDomainName:
    Type: String
    AllowedPattern : "[a-z][a-z0-9\\-]+"

  VolumeSize:
    Type: Number

  InstanceCount:
    Type: String

  InstanceType:
    Type: String
    AllowedValues:
    - m4.10xlarge.elasticsearch
    - m4.2xlarge.elasticsearch
    - m4.4xlarge.elasticsearch
    - m4.large.elasticsearch
    - m4.xlarge.elasticsearch
    - r3.2xlarge.elasticsearch
    - r3.4xlarge.elasticsearch
    - r3.8xlarge.elasticsearch
    - r3.large.elasticsearch
    - r3.xlarge.elasticsearch
    - t2.large.elasticsearch
    - t2.medium.elasticsearch
    - t2.small.elasticsearch

  ZoneAwareness:
    Type: String
    AllowedValues:
    - true
    - false

  EsVersion:
    Type: String

  # Tagging Parameters
  Environment:
    Type: String
    AllowedValues:
      - Production
      - UAT
      - Test

  BusinessUnit:
    Type: String
    AllowedValues:
      - Charitable
      - Corporate
      - Gaming
      - Lotteries
      - Wagering
    ConstraintDescription: Must be Charitable | Corporate | Gaming | Lotteries | Wagering

  Department:
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: BrandName

  Application:
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: ElasticSearch

Conditions:
  IsHA: !Not [!Equals [ InstanceCount, 1 ] ]

Resources:

  ElasticSearchDomain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      DomainName: !Ref SearchDomainName
      ElasticsearchClusterConfig:
        InstanceCount: !Ref InstanceCount
        ZoneAwarenessEnabled: !Ref ZoneAwareness
        InstanceType: !Ref InstanceType
        #DedicatedMasterEnabled: true
        #DedicatedMasterType: "m3.medium.elasticsearch"
        #DedicatedMasterCount: "3"
      EBSOptions:
        EBSEnabled: True
        #Iops: 0
        VolumeSize: !Ref VolumeSize
        VolumeType: gp2
      # SnapshotOptions:
      #   AutomatedSnapshotStartHour: "0"
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
           -
            Effect: "Allow"
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: "es:*"
            Resource: !Sub arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${SearchDomainName}
      ElasticsearchVersion: !Ref EsVersion
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: "true"

      Tags:
        - Key: Name
          Value:  !Sub ${Environment}-${Application}
        - Key: Environment
          Value: !Ref Environment
        - Key: BusinessUnit
          Value: !Ref BusinessUnit
        - Key: Application
          Value: !Ref Application

Outputs:
  DomainEndpoint:
    Description: ElasticSearch Domain EndPoint
    Value: !GetAtt [ElasticSearchDomain, DomainEndpoint]
