# Template created by hash
Description: Creates and Elastic Search Domain for DCHash2 and CNAME in the private DNS Hosted Zone in Route 53

Parameters:

  # Cross-Stack Parameters
  DomainStackName:
    Description: Stack name that built the Route 53 Private Hosted Zone
    Type: String
    Default: UAT-Route53

  #Build Parameters
  BuildBucket:
    Description: The S3 bucket which holds the CloudFormation templates
    Type: String
    Default: dchash2buildbucket

  ElasticSearchTemplateFile:
    Description: Name of the ElasticSearch CloudFormation template file
    Type: String
    Default: ElasticSearch-Domain.yaml

  Route53RecordSetTemplateFile:
    Type: String
    Default: Route53-RecordSet.yaml

  # ElasticSearch Parameters
  SearchDomainName:
    Description: The Name of the ElasticSearch Search Domain to create. No more than 28 characters.
    Type: String
    AllowedPattern : "[a-z][a-z0-9\\-]+"
    Default: uat-DCHash2

  HostName:
    Description: CNAME value for DNS
    Type: String
    Default: DCHash2es

  VolumeSize:
    Description: Size of the EBS volume per instance in GB
    Type: Number
    Default: 35

  InstanceCount:
    Description: Number of instances to create. Must be 1 or an even number
    Type: String
    Default: 2

  EsVersion:
    Description: ElasticSearch Version
    Type: String
    Default: 5.3

  InstanceType:
    Type: String
    AllowedValues:
    - m4.10xlarge.elasticsearch
    - m4.2xlarge.elasticsearch
    - m4.4xlarge.elasticsearch
    - m4.large.elasticsearch
    - m4.xlarge.elasticsearch
    - r3.2xlarge.elasticsearch
    - r3.4xlarge.elasticsearch
    - r3.8xlarge.elasticsearch
    - r3.large.elasticsearch
    - r3.xlarge.elasticsearch
    - t2.large.elasticsearch
    - t2.medium.elasticsearch
    - t2.small.elasticsearch
    Default: t2.small.elasticsearch

  # Tagging Parameters
  Environment:
    Description: Production or NonProduction
    Type: String
    Default: UAT
    AllowedValues:
      - Production
      - UAT
      - Test

  BusinessUnit:
    Description: Some Business Unit
    Type: String
    Default: Gaming
    AllowedValues:
      - Charitable
      - Corporate
      - Gaming
      - Lotteries
      - Wagering
    ConstraintDescription: Must be Charitable | Corporate | Gaming | Lotteries | Wagering

  Department:
    Description: Department
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: BrandName

  Application:
    Description: Specific Application
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: SomePlatform

Conditions:
  IsHA: !Not [ !Equals [ !Ref InstanceCount, 1 ] ]

Resources:

# Create ElasticSearch Domain
  ElasticSearch:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3-ap-southeast-2.amazonaws.com/${BuildBucket}/${ElasticSearchTemplateFile}
      Parameters:
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit
        Department: !Ref Department
        Application: !Ref Application
        SearchDomainName: !Ref SearchDomainName
        VolumeSize: !Ref VolumeSize
        InstanceCount: !Ref InstanceCount
        InstanceType: !Ref InstanceType
        ZoneAwareness: !If [ IsHA, true, false ]
        EsVersion: !Ref EsVersion

# Create CNAME for endpoint
  Route53RecordSet:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3-ap-southeast-2.amazonaws.com/${BuildBucket}/${Route53RecordSetTemplateFile}
      Parameters:
        AliasTarget: ''
        AliasHostedZoneId: ''
        HostedZoneName: ''
        RecordType: CNAME
        HostName: !Ref HostName
        DomainName:
          Fn::ImportValue: !Sub ${DomainStackName}-Private-DomainName
        TTL: 300
        DestinationAddress: !GetAtt [ ElasticSearch, Outputs.DomainEndpoint ]

Outputs:
  DomainEndpoint:
    Description: ElasticSearch Domain EndPoint
    Value: !GetAtt [ElasticSearch, Outputs.DomainEndpoint]
    Export:
      Name: !Sub ${AWS::StackName}-DomainEndpoint

  RecordSet:
    Description: ElasticSearch Record Set
    Value: !GetAtt [ Route53RecordSet, Outputs.RecordSet ]
    Export:
      Name: !Sub ${AWS::StackName}-RecordSet
