# Template created by hash
Description: Security Group for RDS MySQL

Parameters:

# Cross-Stack Parameters
  VPCId:
    Type: String

# Source Security Group Parameters

#  App1-phpSecurityGroup:
#    Type: AWS::EC2::SecurityGroup::Id
#
#  App2-phpSecurityGroup:
#    Type: AWS::EC2::SecurityGroup::Id
#
#  App3-javaSecurityGroup:
#    Type: AWS::EC2::SecurityGroup::Id
#
#  App4-phpSecurityGroup:
#    Type: AWS::EC2::SecurityGroup::Id
#
#  App5-phpSecurityGroup:
#    Type: AWS::EC2::SecurityGroup::Id
#
#  App6-phpSecurityGroup:
#    Type: AWS::EC2::SecurityGroup::Id
#
#  App7-phpSecurityGroup:
#    Type: AWS::EC2::SecurityGroup::Id

# Tagging Parameters
  Environment:
    Type: String
    AllowedValues:
      - Production
      - UAT
      - Test

  BusinessUnit:
    Type: String
    AllowedValues:
      - Charitable
      - Corporate
      - Gaming
      - Lotteries
      - Wagering
    ConstraintDescription: Must be Charitable | Corporate | Gaming | Lotteries | Wagering
  Department:
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: BrandName
  Application:
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: SomePlatform
  Component:
    Type: String
    Default: RDS-MySQL

Resources:

# Create Security Group
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${Application} ${Component} Security Group
      VpcId: !Ref VPCId
      Tags:
      - Key: Name
        Value:  !Sub ${Environment}-${Component}-${Application}
      - Key: Environment
        Value: !Ref Environment
      - Key: BusinessUnit
        Value: !Ref BusinessUnit
      - Key: Application
        Value: !Ref Application

# Add Security Group rules
#  IngressMySQL3306App1-php:
#    Type: AWS::EC2::SecurityGroupIngress
#    Properties:
#      IpProtocol: tcp
#      FromPort: 3306
#      ToPort: 3306
#      SourceSecurityGroupId: !Ref App1-phpSecurityGroup
#      GroupId: !Ref SecurityGroup
#
#  IngressMySQL3306App2-php:
#    Type: AWS::EC2::SecurityGroupIngress
#    Properties:
#      IpProtocol: tcp
#      FromPort: 3306
#      ToPort: 3306
#      SourceSecurityGroupId: !Ref App2-phpSecurityGroup
#      GroupId: !Ref SecurityGroup
#
#  IngressMySQL3306App3-java:
#    Type: AWS::EC2::SecurityGroupIngress
#    Properties:
#      IpProtocol: tcp
#      FromPort: 3306
#      ToPort: 3306
#      SourceSecurityGroupId: !Ref App3-javaSecurityGroup
#      GroupId: !Ref SecurityGroup
#
#  IngressMySQL3306App4-php:
#    Type: AWS::EC2::SecurityGroupIngress
#    Properties:
#      IpProtocol: tcp
#      FromPort: 3306
#      ToPort: 3306
#      SourceSecurityGroupId: !Ref App4-phpSecurityGroup
#      GroupId: !Ref SecurityGroup
#
#  IngressMySQL3306App5-php:
#    Type: AWS::EC2::SecurityGroupIngress
#    Properties:
#      IpProtocol: tcp
#      FromPort: 3306
#      ToPort: 3306
#      SourceSecurityGroupId: !Ref App5-phpSecurityGroup
#      GroupId: !Ref SecurityGroup
#
#  IngressMySQL3306App6-php:
#    Type: AWS::EC2::SecurityGroupIngress
#    Properties:
#      IpProtocol: tcp
#      FromPort: 3306
#      ToPort: 3306
#      SourceSecurityGroupId: !Ref App6-phpSecurityGroup
#      GroupId: !Ref SecurityGroup
#
#  IngressMySQL3306App7-php:
#    Type: AWS::EC2::SecurityGroupIngress
#    Properties:
#      IpProtocol: tcp
#      FromPort: 3306
#      ToPort: 3306
#      SourceSecurityGroupId: !Ref App7-phpSecurityGroup
#      GroupId: !Ref SecurityGroup
#
#  IngressMySQL3306App2-php:
#    Type: AWS::EC2::SecurityGroupIngress
#    Properties:
#      IpProtocol: tcp
#      FromPort: 3306
#      ToPort: 3306
#      SourceSecurityGroupId: !Ref App2-phpSecurityGroup
#      GroupId: !Ref SecurityGroup

Outputs:
  SecurityGroup:
    Description: The RDS Security Group
    Value:  !Ref SecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-SecurityGroup"
