# Template created by hash
Description: Security Group for ElastiCache Redis

Parameters:

  VPCId:
    Type: String

# Source Security Group Id Parameters
#  AmplifySecurityGroup:
#    Type: AWS::EC2::SecurityGroup::Id
#
#  DataConsumerSecurityGroup:
#    Type: AWS::EC2::SecurityGroup::Id
#
#  DataIngestionSecurityGroup:
#    Type: AWS::EC2::SecurityGroup::Id
#
#  KnoxSecurityGroup:
#    Type: AWS::EC2::SecurityGroup::Id
#
#  PosIntegrationSecurityGroup:
#    Type: AWS::EC2::SecurityGroup::Id
#
#  SoldiSecurityGroup:
#    Type: AWS::EC2::SecurityGroup::Id
#
#  SuperPortalSecurityGroup:
#    Type: AWS::EC2::SecurityGroup::Id

# Tagging Parameters
  Environment:
    Type: String
    AllowedValues:
      - Production
      - UAT
      - Test
  BusinessUnit:
    Type: String
    AllowedValues:
      - Charitable
      - Corporate
      - Gaming
      - Lotteries
      - Wagering
    ConstraintDescription: Must be Charitable | Corporate | Gaming | Lotteries | Wagering
  Department:
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: BrandName
  Application:
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: SomePlatform
  Component:
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: ElastiCacheRedis

Resources:
# Create Security Group
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${Component} ${Application} Security Group
      VpcId: !Ref VPCId
      Tags:
      - Key: Name
        Value:  !Sub ${Environment}-${Component}
      - Key: Environment
        Value: !Ref Environment
      - Key: BusinessUnit
        Value: !Ref BusinessUnit
      - Key: Application
        Value: !Ref Application
      - Key: Component
        Value: !Ref Component

# Add rules to Security Group
#  AmplifyIngressRule:
#    Type: AWS::EC2::SecurityGroupIngress
#    Properties:
#      IpProtocol: tcp
#      FromPort: '6379'
#      ToPort: '6379'
#      SourceSecurityGroupId: !Ref AmplifySecurityGroup
#      GroupId: !Ref SecurityGroup
#
#  DataConsumerIngressRule:
#    Type: AWS::EC2::SecurityGroupIngress
#    Properties:
#      IpProtocol: tcp
#      FromPort: '6379'
#      ToPort: '6379'
#      SourceSecurityGroupId: !Ref DataConsumerSecurityGroup
#      GroupId: !Ref SecurityGroup
#
#  DataIngestionIngressRule:
#    Type: AWS::EC2::SecurityGroupIngress
#    Properties:
#      IpProtocol: tcp
#      FromPort: '6379'
#      ToPort: '6379'
#      SourceSecurityGroupId: !Ref DataIngestionSecurityGroup
#      GroupId: !Ref SecurityGroup
#
#  KnoxIngressRule:
#    Type: AWS::EC2::SecurityGroupIngress
#    Properties:
#      IpProtocol: tcp
#      FromPort: '6379'
#      ToPort: '6379'
#      SourceSecurityGroupId: !Ref KnoxSecurityGroup
#      GroupId: !Ref SecurityGroup
#
#  PosIntergationIngressRule:
#    Type: AWS::EC2::SecurityGroupIngress
#    Properties:
#      IpProtocol: tcp
#      FromPort: '6379'
#      ToPort: '6379'
#      SourceSecurityGroupId: !Ref PosIntegrationSecurityGroup
#      GroupId: !Ref SecurityGroup
#
#  SoldiIngressRule:
#    Type: AWS::EC2::SecurityGroupIngress
#    Properties:
#      IpProtocol: tcp
#      FromPort: '6379'
#      ToPort: '6379'
#      SourceSecurityGroupId: !Ref SoldiSecurityGroup
#      GroupId: !Ref SecurityGroup
#
#  SuperPortalIngressRule:
#    Type: AWS::EC2::SecurityGroupIngress
#    Properties:
#      IpProtocol: tcp
#      FromPort: '6379'
#      ToPort: '6379'
#      SourceSecurityGroupId: !Ref SuperPortalSecurityGroup
#      GroupId: !Ref SecurityGroup

Outputs:
  SecurityGroup:
    Description: The ElastiCache Redis Security Group
    Value:  !Ref SecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-SecurityGroup"
