# Template created by hash
Description: Creates Security Groups for DCHash 2
Parameters:

# CloudFormation URL Parameters
  AppApp7-phpFile:
    Type: String
    Description: Filename of the Application Super Portal SG template including file extension
    Default: EC2-SecurityGroup-App-App7-php.yaml
  AppApp4-phpFile:
    Type: String
    Description: Filename of the Application App4-php SG template including file extension
    Default: EC2-SecurityGroup-App-App4-php.yaml
#  AppApp9File:
#    Type: String
#    Description: Filename of the Application App9-phpSG template including file extension
#    Default: EC2-SecurityGroup-App-App9-php.yaml
  AppApp1-phpFile:
    Type: String
    Description: Filename of the Application App1-php SG template including file extension
    Default: EC2-SecurityGroup-App-App1-php.yaml
#  AppApp2-phpFile:
#    Type: String
#    Description: Filename of the Application App4-php SG template including file extension
#    Default: EC2-SecurityGroup-App-App10-php.yaml
  AppApp3-javaFile:
    Type: String
    Description: Filename of the Application Data Ingestion SG template including file extension
    Default: EC2-SecurityGroup-App-App3-java.yaml
  AppApp6-phpFile:
    Type: String
    Description: Filename of the Application App6-php SG template including file extension
    Default: EC2-SecurityGroup-App-App6-php.yaml
  AppApp5-phpFile:
    Type: String
    Description: Filename of the Application POS Integration SG template including file extension
    Default: EC2-SecurityGroup-App-App5-php.yaml
  AppKafkaFile:
    Type: String
    Description: Filename of the Application Kafka SG template including file extension
    Default: EC2-SecurityGroup-App-Kafka.yaml
  AppRabbitMqFile:
    Type: String
    Description: Filename of the Application RabbitMq SG template including file extension
    Default: EC2-SecurityGroup-App-RabbitMq.yaml
  ElastiCacheRedisFile:
    Type: String
    Description: Filename of the ElastiCache Redis SG template including file extension
    Default: EC2-SecurityGroup-ElastiCacheRedis.yaml
  LoadBalancerFile:
    Type: String
    Description: Filename of the LoadBalancer SG template including file extension
    Default: EC2-SecurityGroup-ELB.yaml
  RDSMySqlFile:
    Type: String
    Description: Filename of the RDS SG template including file extension
    Default: EC2-SecurityGroup-RDSMySql.yaml
  BuildBucket:
    Description: Name of the S3 bucket containing the CloudFormation templates
    Type: String
    Default: dchash2buildbucket

# Cross-Stack Parameters
  VPCStackName:
    Description: Stack Name that built the VPC
    Type: String
    Default: DCHash2-VPC

# Tagging Parameters
  Environment:
    Description: Production or NonProduction
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - NonProduction
  BusinessUnit:
    Description: Some Business Unit
    Type: String
    Default: Gaming
    AllowedValues:
      - Charitable
      - Corporate
      - Gaming
      - Lotteries
      - Wagering
    ConstraintDescription: Must be Charitable | Corporate | Gaming | Lotteries | Wagering
  Department:
    Description: Team name Brand Name
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: BrandName
  Application:
    Description: Specific Application
    Type: String
    MinLength: '3'
    MaxLength: '255'
    Default: SomePlatform


# Parameter Grouping
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: CloudFormation Template Files and Location
      Parameters:
      - LoadBalancerFile
      - AppApp1-phpFile
      - AppApp3-javaFile
      - AppApp4-phpFile
      - AppApp5-phpFile
      - AppApp6-phpFile
      - AppApp7-phpFile
#      - AppApp9-phpFile
      - AppKafkaFile
      - AppRabbitMqFile
      - ElastiCacheRedisFile
      - RDSMySqlFile
      - BuildBucket
    - Label:
        default: Cross-Stack Reference Parameters
      Parameters:
      - VPCStackName
    - Label:
        default: Tagging Parameters
      Parameters:
      - Environment
      - BusinessUnit
      - Department
      - Application

Resources:

  # Internet Elastic Load Balancer Security Groups. These all use the same template
  ELBApp1-phpSG:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${BuildBucket}/${LoadBalancerFile}
      Parameters:
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit
        Department: !Ref Department
        Application: !Ref Application
        VPCId:
          Fn::ImportValue: !Sub ${VPCStackName}-VPCID
        Component: App1-php

  ELBApp3-javaSG:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${BuildBucket}/${LoadBalancerFile}
      Parameters:
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit
        Department: !Ref Department
        Application: !Ref Application
        VPCId:
          Fn::ImportValue: !Sub ${VPCStackName}-VPCID
        Component: App3-java

  ELBApp4-phpSG:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${BuildBucket}/${LoadBalancerFile}
      Parameters:
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit
        Department: !Ref Department
        Application: !Ref Application
        VPCId:
          Fn::ImportValue: !Sub ${VPCStackName}-VPCID
        Component: App4-php

  ELBApp5-phpSG:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${BuildBucket}/${LoadBalancerFile}
      Parameters:
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit
        Department: !Ref Department
        Application: !Ref Application
        VPCId:
          Fn::ImportValue: !Sub ${VPCStackName}-VPCID
        Component: App5-php

  ELBApp6-phpSG:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${BuildBucket}/${LoadBalancerFile}
      Parameters:
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit
        Department: !Ref Department
        Application: !Ref Application
        VPCId:
          Fn::ImportValue: !Sub ${VPCStackName}-VPCID
        Component: App6-php

  ELBApp7-phpSG:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${BuildBucket}/${LoadBalancerFile}
      Parameters:
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit
        Department: !Ref Department
        Application: !Ref Application
        VPCId:
          Fn::ImportValue: !Sub ${VPCStackName}-VPCID
        Component: App7-php

  #ELBApp9-phpSG:
  #  Type: AWS::CloudFormation::Stack
  #  Properties:
  #    TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${BuildBucket}/${LoadBalancerFile}
  #    Parameters:
  #      Environment: !Ref Environment
  #      BusinessUnit: !Ref BusinessUnit
  #      Department: !Ref Department
  #      Application: !Ref Application
  #      VPCId:
  #        Fn::ImportValue: !Sub ${VPCStackName}-VPCID
  #      Component: App9-php

  # Application Security Groups

  AppApp1-phpSG:
    Type: AWS::CloudFormation::Stack
    DependsOn: ELBApp1-phpSG
    Properties:
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${BuildBucket}/${AppApp1-phpFile}
      Parameters:
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit
        Department: !Ref Department
        Application: !Ref Application
        VPCId:
          Fn::ImportValue: !Sub ${VPCStackName}-VPCID
        Component: App1-php
        ELBSecurityGroup: !GetAtt [ "ELBApp1-phpSG", "Outputs.SecurityGroup" ]

  AppApp3-javaSG:
    Type: AWS::CloudFormation::Stack
    DependsOn: ELBApp3-javaSG
    Properties:
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${BuildBucket}/${AppApp3-javaFile}
      Parameters:
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit
        Department: !Ref Department
        Application: !Ref Application
        VPCId:
          Fn::ImportValue: !Sub ${VPCStackName}-VPCID
        Component: App3-java
        ELBSecurityGroup: !GetAtt [ "ELBApp3-javaSG", "Outputs.SecurityGroup" ]

  AppApp4-phpSG:
    Type: AWS::CloudFormation::Stack
    DependsOn: ELBApp4-phpSG
    Properties:
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${BuildBucket}/${AppApp4-phpFile}
      Parameters:
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit
        Department: !Ref Department
        Application: !Ref Application
        VPCId:
          Fn::ImportValue: !Sub ${VPCStackName}-VPCID
        Component: App4-php
        ELBSecurityGroup: !GetAtt [ "ELBApp4-phpSG", "Outputs.SecurityGroup" ]

  AppApp5-phpSG:
    Type: AWS::CloudFormation::Stack
    DependsOn: ELBApp5-phpSG
    Properties:
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${BuildBucket}/${AppApp5-phpFile}
      Parameters:
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit
        Department: !Ref Department
        Application: !Ref Application
        VPCId:
          Fn::ImportValue: !Sub ${VPCStackName}-VPCID
        Component: App5-php
        ELBSecurityGroup: !GetAtt [ "ELBApp5-phpSG", "Outputs.SecurityGroup" ]

  AppApp7-phpSG:
    Type: AWS::CloudFormation::Stack
    DependsOn: ELBApp7-phpSG
    Properties:
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${BuildBucket}/${AppApp7-phpFile}
      Parameters:
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit
        Department: !Ref Department
        Application: !Ref Application
        VPCId:
          Fn::ImportValue: !Sub ${VPCStackName}-VPCID
        Component: App7-php
        ELBSecurityGroup: !GetAtt [ "ELBApp7-phpSG", "Outputs.SecurityGroup" ]

#  AppApp9-phpSG:
#    Type: AWS::CloudFormation::Stack
#    DependsOn: ELBApp9-phpSG
#    Properties:
#      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${BuildBucket}/${AppApp9-phpFile}
#      Parameters:
#        Environment: !Ref Environment
#        BusinessUnit: !Ref BusinessUnit
#        Department: !Ref Department
#        Application: !Ref Application
#        VPCId:
#          Fn::ImportValue: !Sub ${VPCStackName}-VPCID
#        Component: App9-php
#        ELBSecurityGroup: !GetAtt [ "ELBApp9-phpSG", "Outputs.SecurityGroup" ]

  AppKafkaSG:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - AppApp1-phpSG
    - AppApp3-javaSG
    - AppApp4-phpSG
    - AppApp5-phpSG
    - AppApp7-phpSG
#    - AppApp9-pphpSG
    Properties:
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${BuildBucket}/${AppKafkaFile}
      Parameters:
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit
        Department: !Ref Department
        Application: !Ref Application
        VPCId:
          Fn::ImportValue: !Sub ${VPCStackName}-VPCID
        Component: Kafka
        AppApp1-phpSecurityGroup: !GetAtt [ "AppApp1-phpSG", "Outputs.SecurityGroup" ]
        AppApp3-javaSecurityGroup: !GetAtt [ "AppApp3-javaSG", "Outputs.SecurityGroup" ]
        AppApp4-phpSecurityGroup: !GetAtt [ "AppApp4-phpSG", "Outputs.SecurityGroup" ]
        AppApp5-phpSecurityGroup: !GetAtt [ "AppApp5-phpSG", "Outputs.SecurityGroup" ]
        AppApp7-phpSecurityGroup: !GetAtt [ "AppApp7-phpSG", "Outputs.SecurityGroup" ]
#        AppApp9-phpSecurityGroup: !GetAtt [ "AppApp9-phpSG", "Outputs.SecurityGroup" ]

  AppRabbitMqSG:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - AppApp3-javaSG
    Properties:
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${BuildBucket}/${AppRabbitMqFile}
      Parameters:
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit
        Department: !Ref Department
        Application: !Ref Application
        VPCId:
          Fn::ImportValue: !Sub ${VPCStackName}-VPCID
        Component: RabbitMq
        AppApp3-javaSecurityGroup: !GetAtt [ "AppApp3-javaSG", "Outputs.SecurityGroup" ]

  # Security Groups for Other VPC Resources
  ElastiCacheRedisSG:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - AppApp1-phpSG
    - AppApp3-javaSG
    - AppApp4-phpSG
    - AppApp5-phpSG
    - AppApp7-phpSG
#    - AppApp9-phpSG
    Properties:
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${BuildBucket}/${ElastiCacheRedisFile}
      Parameters:
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit
        Department: !Ref Department
        Application: !Ref Application
        VPCId:
          Fn::ImportValue: !Sub ${VPCStackName}-VPCID
        Component: ElastiCacheRedis
        AppApp1-phpSecurityGroup: !GetAtt [ "AppApp1-phpSG", "Outputs.SecurityGroup" ]
        AppApp3-javaSecurityGroup: !GetAtt [ "AppApp3-javaSG", "Outputs.SecurityGroup" ]
        AppApp4-phpSecurityGroup: !GetAtt [ "AppApp4-phpSG", "Outputs.SecurityGroup" ]
        AppApp5-phpSecurityGroup: !GetAtt [ "AppApp5-phpSG", "Outputs.SecurityGroup" ]
        AppApp7-phpSecurityGroup: !GetAtt [ "AppApp7-phpSG", "Outputs.SecurityGroup" ]
#        AppApp9-phpSecurityGroup: !GetAtt [ "AppApp9-phpSG", "Outputs.SecurityGroup" ]

  RDSMySqlSG:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - AppApp1-phpSG
    - AppApp3-javaSG
    - AppApp4-phpSG
    - AppApp5-phpSG
    - AppApp7-phpSG
#    - AppApp9-phpSG
    Properties:
      TemplateURL: !Join [ "/", [ "https://s3-ap-southeast-2.amazonaws.com", !Ref BuildBucket, !Ref RDSMySqlFile ]]
      Parameters:
        Environment: !Ref Environment
        BusinessUnit: !Ref BusinessUnit
        Department: !Ref Department
        Application: !Ref Application
        VPCId:
          Fn::ImportValue: !Sub ${VPCStackName}-VPCID
        Component: RDSMySql
        AppApp1-phpSecurityGroup: !GetAtt [ "AppApp1-phpSG", "Outputs.SecurityGroup" ]
        AppApp3-javaSecurityGroup: !GetAtt [ "AppApp3-javaSG", "Outputs.SecurityGroup" ]
        AppApp4-phpSecurityGroup: !GetAtt [ "AppApp4-phpSG", "Outputs.SecurityGroup" ]
        AppApp5-phpSecurityGroup: !GetAtt [ "AppApp5-phpSG", "Outputs.SecurityGroup" ]
        AppApp7-phpSecurityGroup: !GetAtt [ "AppApp7-phpSG", "Outputs.SecurityGroup" ]
#        AppApp9-phpSecurityGroup: !GetAtt [ "AppApp9-phpSG", "Outputs.SecurityGroup" ]

Outputs:

  ELBApp1-phpSG:
    Description: Load Balancer App1-php Security Group ID
    Value: !GetAtt [ "ELBApp1-phpSG", "Outputs.SecurityGroup" ]
    Export:
      Name: !Sub "${AWS::StackName}-ELBApp1-phpSG"

  AppApp1-phpSG:
    Description: Application App1-php Security Group ID
    Value: !GetAtt [ "AppApp1-phpSG", "Outputs.SecurityGroup" ]
    Export:
      Name: !Sub "${AWS::StackName}-AppApp1-phpSG"

  ELBApp3-javaSG:
    Description: Load Balancer App3-java Security Group ID
    Value: !GetAtt [ "ELBApp3-javaSG", "Outputs.SecurityGroup" ]
    Export:
      Name: !Sub "${AWS::StackName}-ELBApp3-javaSG"

  AppApp3-javaSG:
    Description: Application App3-java Security Group ID
    Value: !GetAtt [ "AppApp3-javaSG", "Outputs.SecurityGroup" ]
    Export:
      Name: !Sub "${AWS::StackName}-AppApp3-javaSG"

  ELBApp4-phpSG:
    Description: Load Balancer App4-php Security Group ID
    Value: !GetAtt [ "ELBApp4-phpSG", "Outputs.SecurityGroup" ]
    Export:
      Name: !Sub "${AWS::StackName}-ELBApp4-phpSG"

  AppApp4-phpSG:
    Description: Application App4-php Security Group ID
    Value: !GetAtt [ "AppApp4-phpSG", "Outputs.SecurityGroup" ]
    Export:
      Name: !Sub "${AWS::StackName}-AppApp4-phpSG"

  ELBApp5-phpSG:
    Description: Load Balancer App5-php Security Group ID
    Value: !GetAtt [ "ELBApp5-phpSG", "Outputs.SecurityGroup" ]
    Export:
      Name: !Sub "${AWS::StackName}-ELBApp5-phpSG"

  AppApp5-phpSG:
    Description: Application App5-php Security Group ID
    Value: !GetAtt [ "AppApp5-phpSG", "Outputs.SecurityGroup" ]
    Export:
      Name: !Sub "${AWS::StackName}-AppApp5-phpSG"

  ELBApp7-phpSG:
    Description: Load Balancer App7-php Security Group ID
    Value: !GetAtt [ "ELBApp7-phpSG", "Outputs.SecurityGroup" ]
    Export:
      Name: !Sub "${AWS::StackName}-ELBApp7-phpSG"

  AppApp7-phpSG:
    Description: Application App7-php Security Group ID
    Value: !GetAtt [ "AppApp7-phpSG", "Outputs.SecurityGroup" ]
    Export:
      Name: !Sub "${AWS::StackName}-AppApp7-phpSG"

#  ELBApp9-phpSG:
#    Description: Load Balancer App9-php Security Group ID
#    Value: !GetAtt [ "ELBApp9-phpSG", "Outputs.SecurityGroup" ]
#    Export:
#      Name: !Sub "${AWS::StackName}-ELBApp9-phpSG"

#  AppApp9-phpSG:
#    Description: Application App9-php Security Group ID
#    Value: !GetAtt [ "AppApp9-phpSG", "Outputs.SecurityGroup" ]
#    Export:
#      Name: !Sub "${AWS::StackName}-AppApp9-phpSG"

  AppKafkaSG:
    Description: Application Kafka Security Group ID
    Value: !GetAtt [ "AppKafkaSG", "Outputs.SecurityGroup" ]
    Export:
      Name: !Sub "${AWS::StackName}-AppKafkaSG"

  AppRabbitMqSG:
    Description: Application RabbitMq Security Group ID
    Value: !GetAtt [ "AppRabbitMqSG", "Outputs.SecurityGroup" ]
    Export:
      Name: !Sub "${AWS::StackName}-AppRabbitMqSG"

  ElastiCacheRedisSG:
    Description: ElastiCache Redis Security Group ID
    Value: !GetAtt [ "ElastiCacheRedisSG", "Outputs.SecurityGroup" ]
    Export:
      Name: !Sub "${AWS::StackName}-ElastiCacheRedisSG"
  RDSMySqlSG:
    Description: RDS MySql Security Group ID
    Value: !GetAtt [ "RDSMySqlSG", "Outputs.SecurityGroup" ]
    Export:
      Name: !Sub "${AWS::StackName}-RDSMySqlSG"
